### ISSUE TITLE
5_undefinded

### ISSUE THREAD

**Issue by iamrandle** [pahjay/altum#3] opened 2017-08-04 20:51 UTC
Console reads:

"deleting 5_undefined_bronze
deleting 5_undefined_gold
deleting 5_undefined_silver"

at some point after a user joins the lobby.

**Comment by ryanpag3** [comment] 2017-08-04 23:04
I can't seem to reproduce this on my end. Maybe it's specific to your branch?

**Comment by ryanpag3** [comment] 2017-08-11 20:28
Issue was due to @iamrandle having a out-of-date game-list schema. Local bug only, closing issue.

**Closed as completed by ryanpag3** 2017-08-11 20:28 UTC
Labels: bug
